variable: 
 DOCKER_DRIVER: overlay
 USER_GITLAB: aminesghir
 APP_NAME: demo 
 REPO: eureka

stages: 
 - build 
 - docker

maven-build:
 image: maven:3-jdk-8
 stage: build
 script : "mvn package"
 actifact: 
    path: 
    - target/*.jar

docker-build: 
 stage: docker
 script: 
 - docker build 
 - clean cache 



